service: s3-file-uploader

provider: 
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: sa-east-1

custom:
  fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}

plugins: 
  - serverless-iam-roles-per-function

functions:
  s3FileUploader:
    handler: src/upload.handler
    name: s3-file-uploader
    description: A lambda handler that uploads file to an S3 Bucket based on an API Gateway Trigger
    timeout: 60 # seconds
    memorySize: 128 #mb
    events:
      - http: 
          path: images
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 's3:Put*'
        Resource: arn:aws:s3:::${self:custom.fileUploadBucketName}/*
    environment:
      FILE_UPLOAD_BUCKET_NAME: ${self:custom.fileUploadBucketName}

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl: PublicRead